### ISSUE TITLE
Child process spawn error

### ISSUE THREAD

**Issue by gavinisagi** [Daemon-Technologies/Mining-Local-Server#15]
(node:21420) UnhandledPromiseRejectionWarning: Error: spawn ./stacks-node EACCES
    at Process.ChildProcess._handle.onexit (internal/child_process.js:268:19)
    at onErrorNT (internal/child_process.js:468:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:21420) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:21420) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by gavinisagi** [comment]
Caused by permission of system command. Should add execute permission to stacks-node file

**Comment by gavinisagi** [comment]
use ```chmod +x stacks-node```
release in 1.0.0 Tag
